version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: backgammon-mongo-test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: backgammon_test

  test-runner:
    build:
      context: .
      dockerfile: Backgammon.IntegrationTests/Dockerfile
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - Mongo__ConnectionString=mongodb://mongodb:27017
    command: ["dotnet", "test", "Backgammon.IntegrationTests/Backgammon.IntegrationTests.csproj", "--logger:trx"]
